package com.sundeinfo.kd.zs.dao;

import com.sundeinfo.kd.zs.dao.model.RolePermissionExample;
import com.sundeinfo.kd.zs.dao.model.RolePermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    long countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int insert(RolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int insertSelective(RolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    List<RolePermissionKey> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RolePermissionKey record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RolePermissionKey record, @Param("example") RolePermissionExample example);
}