package com.sundeinfo.kd.zs.dao;

import com.sundeinfo.kd.zs.dao.model.SchoolRecruitSum;
import com.sundeinfo.kd.zs.dao.model.SchoolRecruitSumExample;
import com.sundeinfo.kd.zs.dao.model.SchoolRecruitSumKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolRecruitSumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    long countByExample(SchoolRecruitSumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    int deleteByExample(SchoolRecruitSumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SchoolRecruitSumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    int insert(SchoolRecruitSum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    int insertSelective(SchoolRecruitSum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    List<SchoolRecruitSum> selectByExample(SchoolRecruitSumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    SchoolRecruitSum selectByPrimaryKey(SchoolRecruitSumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SchoolRecruitSum record, @Param("example") SchoolRecruitSumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SchoolRecruitSum record, @Param("example") SchoolRecruitSumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SchoolRecruitSum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SchoolRecruitSum record);
}