package com.sundeinfo.kd.zs.dao;

import com.sundeinfo.kd.zs.dao.model.SchoolGroup;
import com.sundeinfo.kd.zs.dao.model.SchoolGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group
     *
     * @mbg.generated
     */
    long countByExample(SchoolGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group
     *
     * @mbg.generated
     */
    int deleteByExample(SchoolGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group
     *
     * @mbg.generated
     */
    int insert(SchoolGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group
     *
     * @mbg.generated
     */
    int insertSelective(SchoolGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group
     *
     * @mbg.generated
     */
    List<SchoolGroup> selectByExample(SchoolGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group
     *
     * @mbg.generated
     */
    SchoolGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SchoolGroup record, @Param("example") SchoolGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SchoolGroup record, @Param("example") SchoolGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SchoolGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SchoolGroup record);
}