package com.sundeinfo.kd.zs.dao;

import com.sundeinfo.kd.zs.dao.model.SchoolRecruitCountingExample;
import com.sundeinfo.kd.zs.dao.model.SchoolRecruitCounting;
import com.sundeinfo.kd.zs.dao.model.SchoolRecruitCountingKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SchoolRecruitCountingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_counting
     *
     * @mbg.generated
     */
    long countByExample(SchoolRecruitCountingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_counting
     *
     * @mbg.generated
     */
    int deleteByExample(SchoolRecruitCountingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_counting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SchoolRecruitCountingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_counting
     *
     * @mbg.generated
     */
    int insert(SchoolRecruitCounting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_counting
     *
     * @mbg.generated
     */
    int insertSelective(SchoolRecruitCounting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_counting
     *
     * @mbg.generated
     */
    List<SchoolRecruitCounting> selectByExample(SchoolRecruitCountingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_counting
     *
     * @mbg.generated
     */
    SchoolRecruitCounting selectByPrimaryKey(SchoolRecruitCountingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_counting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SchoolRecruitCounting record, @Param("example") SchoolRecruitCountingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_counting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SchoolRecruitCounting record, @Param("example") SchoolRecruitCountingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_counting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SchoolRecruitCounting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_counting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SchoolRecruitCounting record);
}