package com.sundeinfo.kd.zs.dao;

import com.sundeinfo.kd.zs.dao.model.SchoolRecruitPlan;
import com.sundeinfo.kd.zs.dao.model.SchoolRecruitPlanExample;
import com.sundeinfo.kd.zs.dao.model.SchoolRecruitPlanKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolRecruitPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    long countByExample(SchoolRecruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    int deleteByExample(SchoolRecruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SchoolRecruitPlanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    int insert(SchoolRecruitPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    int insertSelective(SchoolRecruitPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    List<SchoolRecruitPlan> selectByExample(SchoolRecruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    SchoolRecruitPlan selectByPrimaryKey(SchoolRecruitPlanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SchoolRecruitPlan record, @Param("example") SchoolRecruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SchoolRecruitPlan record, @Param("example") SchoolRecruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SchoolRecruitPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SchoolRecruitPlan record);
}