package com.sundeinfo.kd.zs.dao;

import com.sundeinfo.kd.zs.dao.model.SchoolGroupDetail;
import com.sundeinfo.kd.zs.dao.model.SchoolGroupDetailExample;
import com.sundeinfo.kd.zs.dao.model.SchoolGroupDetailKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolGroupDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group_detail
     *
     * @mbg.generated
     */
    long countByExample(SchoolGroupDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group_detail
     *
     * @mbg.generated
     */
    int deleteByExample(SchoolGroupDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SchoolGroupDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group_detail
     *
     * @mbg.generated
     */
    int insert(SchoolGroupDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group_detail
     *
     * @mbg.generated
     */
    int insertSelective(SchoolGroupDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group_detail
     *
     * @mbg.generated
     */
    List<SchoolGroupDetail> selectByExample(SchoolGroupDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group_detail
     *
     * @mbg.generated
     */
    SchoolGroupDetail selectByPrimaryKey(SchoolGroupDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SchoolGroupDetail record, @Param("example") SchoolGroupDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SchoolGroupDetail record, @Param("example") SchoolGroupDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SchoolGroupDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SchoolGroupDetail record);
}