package com.sundeinfo.kd.zs.dao;

import com.sundeinfo.kd.zs.dao.model.SchoolTeacher;
import com.sundeinfo.kd.zs.dao.model.SchoolTeacherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_teacher
     *
     * @mbg.generated
     */
    long countByExample(SchoolTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_teacher
     *
     * @mbg.generated
     */
    int deleteByExample(SchoolTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_teacher
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_teacher
     *
     * @mbg.generated
     */
    int insert(SchoolTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_teacher
     *
     * @mbg.generated
     */
    int insertSelective(SchoolTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_teacher
     *
     * @mbg.generated
     */
    List<SchoolTeacher> selectByExample(SchoolTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_teacher
     *
     * @mbg.generated
     */
    SchoolTeacher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_teacher
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SchoolTeacher record, @Param("example") SchoolTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_teacher
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SchoolTeacher record, @Param("example") SchoolTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_teacher
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SchoolTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_teacher
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SchoolTeacher record);
}