package com.sundeinfo.kd.zs.dao.model;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_permission.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_permission.permissionCode
     *
     * @mbg.generated
     */
    private String permissioncode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_permission.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbg.generated
     */
    public Permission(Integer id, String permissioncode, String description) {
        this.id = id;
        this.permissioncode = permissioncode;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbg.generated
     */
    public Permission() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_permission.id
     *
     * @return the value of u_permission.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_permission.id
     *
     * @param id the value for u_permission.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_permission.permissionCode
     *
     * @return the value of u_permission.permissionCode
     *
     * @mbg.generated
     */
    public String getPermissioncode() {
        return permissioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_permission.permissionCode
     *
     * @param permissioncode the value for u_permission.permissionCode
     *
     * @mbg.generated
     */
    public void setPermissioncode(String permissioncode) {
        this.permissioncode = permissioncode == null ? null : permissioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_permission.description
     *
     * @return the value of u_permission.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_permission.description
     *
     * @param description the value for u_permission.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}