package com.sundeinfo.kd.zs.dao.model;

public class SchoolGroupDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_school_group_detail.groupId
     *
     * @mbg.generated
     */
    private Integer groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_school_group_detail.schoolId
     *
     * @mbg.generated
     */
    private Integer schoolid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group_detail
     *
     * @mbg.generated
     */
    public SchoolGroupDetailKey(Integer groupid, Integer schoolid) {
        this.groupid = groupid;
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school_group_detail
     *
     * @mbg.generated
     */
    public SchoolGroupDetailKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_school_group_detail.groupId
     *
     * @return the value of m_school_group_detail.groupId
     *
     * @mbg.generated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_school_group_detail.groupId
     *
     * @param groupid the value for m_school_group_detail.groupId
     *
     * @mbg.generated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_school_group_detail.schoolId
     *
     * @return the value of m_school_group_detail.schoolId
     *
     * @mbg.generated
     */
    public Integer getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_school_group_detail.schoolId
     *
     * @param schoolid the value for m_school_group_detail.schoolId
     *
     * @mbg.generated
     */
    public void setSchoolid(Integer schoolid) {
        this.schoolid = schoolid;
    }
}