package com.sundeinfo.kd.zs.dao.model;

import java.util.Date;

public class School {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_school.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_school.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_school.shortName
     *
     * @mbg.generated
     */
    private String shortname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_school.areaId
     *
     * @mbg.generated
     */
    private Integer areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_school.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_school.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_school.isdelete
     *
     * @mbg.generated
     */
    private Byte isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_school.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_school.createby
     *
     * @mbg.generated
     */
    private Integer createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_school.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_school.updateby
     *
     * @mbg.generated
     */
    private Integer updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school
     *
     * @mbg.generated
     */
    public School(Integer id, String name, String shortname, Integer areaid, String address, String tel, Byte isdelete, Date createtime, Integer createby, Date updatetime, Integer updateby) {
        this.id = id;
        this.name = name;
        this.shortname = shortname;
        this.areaid = areaid;
        this.address = address;
        this.tel = tel;
        this.isdelete = isdelete;
        this.createtime = createtime;
        this.createby = createby;
        this.updatetime = updatetime;
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_school
     *
     * @mbg.generated
     */
    public School() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_school.id
     *
     * @return the value of m_school.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_school.id
     *
     * @param id the value for m_school.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_school.name
     *
     * @return the value of m_school.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_school.name
     *
     * @param name the value for m_school.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_school.shortName
     *
     * @return the value of m_school.shortName
     *
     * @mbg.generated
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_school.shortName
     *
     * @param shortname the value for m_school.shortName
     *
     * @mbg.generated
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_school.areaId
     *
     * @return the value of m_school.areaId
     *
     * @mbg.generated
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_school.areaId
     *
     * @param areaid the value for m_school.areaId
     *
     * @mbg.generated
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_school.address
     *
     * @return the value of m_school.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_school.address
     *
     * @param address the value for m_school.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_school.tel
     *
     * @return the value of m_school.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_school.tel
     *
     * @param tel the value for m_school.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_school.isdelete
     *
     * @return the value of m_school.isdelete
     *
     * @mbg.generated
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_school.isdelete
     *
     * @param isdelete the value for m_school.isdelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_school.createtime
     *
     * @return the value of m_school.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_school.createtime
     *
     * @param createtime the value for m_school.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_school.createby
     *
     * @return the value of m_school.createby
     *
     * @mbg.generated
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_school.createby
     *
     * @param createby the value for m_school.createby
     *
     * @mbg.generated
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_school.updatetime
     *
     * @return the value of m_school.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_school.updatetime
     *
     * @param updatetime the value for m_school.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_school.updateby
     *
     * @return the value of m_school.updateby
     *
     * @mbg.generated
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_school.updateby
     *
     * @param updateby the value for m_school.updateby
     *
     * @mbg.generated
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }
}