package com.sundeinfo.kd.zs.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SchoolRecruitSeasonExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    public SchoolRecruitSeasonExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRecruityearIsNull() {
            addCriterion("recruitYear is null");
            return (Criteria) this;
        }

        public Criteria andRecruityearIsNotNull() {
            addCriterion("recruitYear is not null");
            return (Criteria) this;
        }

        public Criteria andRecruityearEqualTo(String value) {
            addCriterion("recruitYear =", value, "recruityear");
            return (Criteria) this;
        }

        public Criteria andRecruityearNotEqualTo(String value) {
            addCriterion("recruitYear <>", value, "recruityear");
            return (Criteria) this;
        }

        public Criteria andRecruityearGreaterThan(String value) {
            addCriterion("recruitYear >", value, "recruityear");
            return (Criteria) this;
        }

        public Criteria andRecruityearGreaterThanOrEqualTo(String value) {
            addCriterion("recruitYear >=", value, "recruityear");
            return (Criteria) this;
        }

        public Criteria andRecruityearLessThan(String value) {
            addCriterion("recruitYear <", value, "recruityear");
            return (Criteria) this;
        }

        public Criteria andRecruityearLessThanOrEqualTo(String value) {
            addCriterion("recruitYear <=", value, "recruityear");
            return (Criteria) this;
        }

        public Criteria andRecruityearLike(String value) {
            addCriterion("recruitYear like", value, "recruityear");
            return (Criteria) this;
        }

        public Criteria andRecruityearNotLike(String value) {
            addCriterion("recruitYear not like", value, "recruityear");
            return (Criteria) this;
        }

        public Criteria andRecruityearIn(List<String> values) {
            addCriterion("recruitYear in", values, "recruityear");
            return (Criteria) this;
        }

        public Criteria andRecruityearNotIn(List<String> values) {
            addCriterion("recruitYear not in", values, "recruityear");
            return (Criteria) this;
        }

        public Criteria andRecruityearBetween(String value1, String value2) {
            addCriterion("recruitYear between", value1, value2, "recruityear");
            return (Criteria) this;
        }

        public Criteria andRecruityearNotBetween(String value1, String value2) {
            addCriterion("recruitYear not between", value1, value2, "recruityear");
            return (Criteria) this;
        }

        public Criteria andRecruitseasonIsNull() {
            addCriterion("recruitSeason is null");
            return (Criteria) this;
        }

        public Criteria andRecruitseasonIsNotNull() {
            addCriterion("recruitSeason is not null");
            return (Criteria) this;
        }

        public Criteria andRecruitseasonEqualTo(Boolean value) {
            addCriterion("recruitSeason =", value, "recruitseason");
            return (Criteria) this;
        }

        public Criteria andRecruitseasonNotEqualTo(Boolean value) {
            addCriterion("recruitSeason <>", value, "recruitseason");
            return (Criteria) this;
        }

        public Criteria andRecruitseasonGreaterThan(Boolean value) {
            addCriterion("recruitSeason >", value, "recruitseason");
            return (Criteria) this;
        }

        public Criteria andRecruitseasonGreaterThanOrEqualTo(Boolean value) {
            addCriterion("recruitSeason >=", value, "recruitseason");
            return (Criteria) this;
        }

        public Criteria andRecruitseasonLessThan(Boolean value) {
            addCriterion("recruitSeason <", value, "recruitseason");
            return (Criteria) this;
        }

        public Criteria andRecruitseasonLessThanOrEqualTo(Boolean value) {
            addCriterion("recruitSeason <=", value, "recruitseason");
            return (Criteria) this;
        }

        public Criteria andRecruitseasonIn(List<Boolean> values) {
            addCriterion("recruitSeason in", values, "recruitseason");
            return (Criteria) this;
        }

        public Criteria andRecruitseasonNotIn(List<Boolean> values) {
            addCriterion("recruitSeason not in", values, "recruitseason");
            return (Criteria) this;
        }

        public Criteria andRecruitseasonBetween(Boolean value1, Boolean value2) {
            addCriterion("recruitSeason between", value1, value2, "recruitseason");
            return (Criteria) this;
        }

        public Criteria andRecruitseasonNotBetween(Boolean value1, Boolean value2) {
            addCriterion("recruitSeason not between", value1, value2, "recruitseason");
            return (Criteria) this;
        }

        public Criteria andRecruitstartdateIsNull() {
            addCriterion("recruitStartDate is null");
            return (Criteria) this;
        }

        public Criteria andRecruitstartdateIsNotNull() {
            addCriterion("recruitStartDate is not null");
            return (Criteria) this;
        }

        public Criteria andRecruitstartdateEqualTo(Date value) {
            addCriterionForJDBCDate("recruitStartDate =", value, "recruitstartdate");
            return (Criteria) this;
        }

        public Criteria andRecruitstartdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("recruitStartDate <>", value, "recruitstartdate");
            return (Criteria) this;
        }

        public Criteria andRecruitstartdateGreaterThan(Date value) {
            addCriterionForJDBCDate("recruitStartDate >", value, "recruitstartdate");
            return (Criteria) this;
        }

        public Criteria andRecruitstartdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("recruitStartDate >=", value, "recruitstartdate");
            return (Criteria) this;
        }

        public Criteria andRecruitstartdateLessThan(Date value) {
            addCriterionForJDBCDate("recruitStartDate <", value, "recruitstartdate");
            return (Criteria) this;
        }

        public Criteria andRecruitstartdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("recruitStartDate <=", value, "recruitstartdate");
            return (Criteria) this;
        }

        public Criteria andRecruitstartdateIn(List<Date> values) {
            addCriterionForJDBCDate("recruitStartDate in", values, "recruitstartdate");
            return (Criteria) this;
        }

        public Criteria andRecruitstartdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("recruitStartDate not in", values, "recruitstartdate");
            return (Criteria) this;
        }

        public Criteria andRecruitstartdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("recruitStartDate between", value1, value2, "recruitstartdate");
            return (Criteria) this;
        }

        public Criteria andRecruitstartdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("recruitStartDate not between", value1, value2, "recruitstartdate");
            return (Criteria) this;
        }

        public Criteria andRecruitenddateIsNull() {
            addCriterion("recruitEndDate is null");
            return (Criteria) this;
        }

        public Criteria andRecruitenddateIsNotNull() {
            addCriterion("recruitEndDate is not null");
            return (Criteria) this;
        }

        public Criteria andRecruitenddateEqualTo(Date value) {
            addCriterionForJDBCDate("recruitEndDate =", value, "recruitenddate");
            return (Criteria) this;
        }

        public Criteria andRecruitenddateNotEqualTo(Date value) {
            addCriterionForJDBCDate("recruitEndDate <>", value, "recruitenddate");
            return (Criteria) this;
        }

        public Criteria andRecruitenddateGreaterThan(Date value) {
            addCriterionForJDBCDate("recruitEndDate >", value, "recruitenddate");
            return (Criteria) this;
        }

        public Criteria andRecruitenddateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("recruitEndDate >=", value, "recruitenddate");
            return (Criteria) this;
        }

        public Criteria andRecruitenddateLessThan(Date value) {
            addCriterionForJDBCDate("recruitEndDate <", value, "recruitenddate");
            return (Criteria) this;
        }

        public Criteria andRecruitenddateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("recruitEndDate <=", value, "recruitenddate");
            return (Criteria) this;
        }

        public Criteria andRecruitenddateIn(List<Date> values) {
            addCriterionForJDBCDate("recruitEndDate in", values, "recruitenddate");
            return (Criteria) this;
        }

        public Criteria andRecruitenddateNotIn(List<Date> values) {
            addCriterionForJDBCDate("recruitEndDate not in", values, "recruitenddate");
            return (Criteria) this;
        }

        public Criteria andRecruitenddateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("recruitEndDate between", value1, value2, "recruitenddate");
            return (Criteria) this;
        }

        public Criteria andRecruitenddateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("recruitEndDate not between", value1, value2, "recruitenddate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("isdelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("isdelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Boolean value) {
            addCriterion("isdelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Boolean value) {
            addCriterion("isdelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Boolean value) {
            addCriterion("isdelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isdelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Boolean value) {
            addCriterion("isdelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("isdelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Boolean> values) {
            addCriterion("isdelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Boolean> values) {
            addCriterion("isdelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("isdelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isdelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("createby is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("createby is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(Integer value) {
            addCriterion("createby =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(Integer value) {
            addCriterion("createby <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(Integer value) {
            addCriterion("createby >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(Integer value) {
            addCriterion("createby >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(Integer value) {
            addCriterion("createby <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(Integer value) {
            addCriterion("createby <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<Integer> values) {
            addCriterion("createby in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<Integer> values) {
            addCriterion("createby not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(Integer value1, Integer value2) {
            addCriterion("createby between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(Integer value1, Integer value2) {
            addCriterion("createby not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNull() {
            addCriterion("updateby is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNotNull() {
            addCriterion("updateby is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyEqualTo(Integer value) {
            addCriterion("updateby =", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotEqualTo(Integer value) {
            addCriterion("updateby <>", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThan(Integer value) {
            addCriterion("updateby >", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThanOrEqualTo(Integer value) {
            addCriterion("updateby >=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThan(Integer value) {
            addCriterion("updateby <", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThanOrEqualTo(Integer value) {
            addCriterion("updateby <=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIn(List<Integer> values) {
            addCriterion("updateby in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotIn(List<Integer> values) {
            addCriterion("updateby not in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyBetween(Integer value1, Integer value2) {
            addCriterion("updateby between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotBetween(Integer value1, Integer value2) {
            addCriterion("updateby not between", value1, value2, "updateby");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}