package com.sundeinfo.kd.zs.dao.model;

import java.util.Date;

public class SchoolRecruitSum extends SchoolRecruitSumKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_sum.undergraduatePeople
     *
     * @mbg.generated
     */
    private Integer undergraduatepeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_sum.technicalPeople
     *
     * @mbg.generated
     */
    private Integer technicalpeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_sum.gkPeople
     *
     * @mbg.generated
     */
    private Integer gkpeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_sum.revise
     *
     * @mbg.generated
     */
    private Boolean revise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_sum.isdelete
     *
     * @mbg.generated
     */
    private Boolean isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_sum.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_sum.createby
     *
     * @mbg.generated
     */
    private Integer createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_sum.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_sum.updateby
     *
     * @mbg.generated
     */
    private Integer updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    public SchoolRecruitSum(Integer seasonid, Integer schoolid, Integer undergraduatepeople, Integer technicalpeople, Integer gkpeople, Boolean revise, Boolean isdelete, Date createtime, Integer createby, Date updatetime, Integer updateby) {
        super(seasonid, schoolid);
        this.undergraduatepeople = undergraduatepeople;
        this.technicalpeople = technicalpeople;
        this.gkpeople = gkpeople;
        this.revise = revise;
        this.isdelete = isdelete;
        this.createtime = createtime;
        this.createby = createby;
        this.updatetime = updatetime;
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    public SchoolRecruitSum() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_sum.undergraduatePeople
     *
     * @return the value of b_school_recruit_sum.undergraduatePeople
     *
     * @mbg.generated
     */
    public Integer getUndergraduatepeople() {
        return undergraduatepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_sum.undergraduatePeople
     *
     * @param undergraduatepeople the value for b_school_recruit_sum.undergraduatePeople
     *
     * @mbg.generated
     */
    public void setUndergraduatepeople(Integer undergraduatepeople) {
        this.undergraduatepeople = undergraduatepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_sum.technicalPeople
     *
     * @return the value of b_school_recruit_sum.technicalPeople
     *
     * @mbg.generated
     */
    public Integer getTechnicalpeople() {
        return technicalpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_sum.technicalPeople
     *
     * @param technicalpeople the value for b_school_recruit_sum.technicalPeople
     *
     * @mbg.generated
     */
    public void setTechnicalpeople(Integer technicalpeople) {
        this.technicalpeople = technicalpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_sum.gkPeople
     *
     * @return the value of b_school_recruit_sum.gkPeople
     *
     * @mbg.generated
     */
    public Integer getGkpeople() {
        return gkpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_sum.gkPeople
     *
     * @param gkpeople the value for b_school_recruit_sum.gkPeople
     *
     * @mbg.generated
     */
    public void setGkpeople(Integer gkpeople) {
        this.gkpeople = gkpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_sum.revise
     *
     * @return the value of b_school_recruit_sum.revise
     *
     * @mbg.generated
     */
    public Boolean getRevise() {
        return revise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_sum.revise
     *
     * @param revise the value for b_school_recruit_sum.revise
     *
     * @mbg.generated
     */
    public void setRevise(Boolean revise) {
        this.revise = revise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_sum.isdelete
     *
     * @return the value of b_school_recruit_sum.isdelete
     *
     * @mbg.generated
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_sum.isdelete
     *
     * @param isdelete the value for b_school_recruit_sum.isdelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_sum.createtime
     *
     * @return the value of b_school_recruit_sum.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_sum.createtime
     *
     * @param createtime the value for b_school_recruit_sum.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_sum.createby
     *
     * @return the value of b_school_recruit_sum.createby
     *
     * @mbg.generated
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_sum.createby
     *
     * @param createby the value for b_school_recruit_sum.createby
     *
     * @mbg.generated
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_sum.updatetime
     *
     * @return the value of b_school_recruit_sum.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_sum.updatetime
     *
     * @param updatetime the value for b_school_recruit_sum.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_sum.updateby
     *
     * @return the value of b_school_recruit_sum.updateby
     *
     * @mbg.generated
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_sum.updateby
     *
     * @param updateby the value for b_school_recruit_sum.updateby
     *
     * @mbg.generated
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }
}