package com.sundeinfo.kd.zs.dao.model;

public class SchoolRecruitSumKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_sum.seasonId
     *
     * @mbg.generated
     */
    private Integer seasonid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_sum.schoolId
     *
     * @mbg.generated
     */
    private Integer schoolid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    public SchoolRecruitSumKey(Integer seasonid, Integer schoolid) {
        this.seasonid = seasonid;
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_sum
     *
     * @mbg.generated
     */
    public SchoolRecruitSumKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_sum.seasonId
     *
     * @return the value of b_school_recruit_sum.seasonId
     *
     * @mbg.generated
     */
    public Integer getSeasonid() {
        return seasonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_sum.seasonId
     *
     * @param seasonid the value for b_school_recruit_sum.seasonId
     *
     * @mbg.generated
     */
    public void setSeasonid(Integer seasonid) {
        this.seasonid = seasonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_sum.schoolId
     *
     * @return the value of b_school_recruit_sum.schoolId
     *
     * @mbg.generated
     */
    public Integer getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_sum.schoolId
     *
     * @param schoolid the value for b_school_recruit_sum.schoolId
     *
     * @mbg.generated
     */
    public void setSchoolid(Integer schoolid) {
        this.schoolid = schoolid;
    }
}