package com.sundeinfo.kd.zs.dao.model;

import java.util.Date;

public class SchoolRecruitSeason {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_season.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_season.recruitYear
     *
     * @mbg.generated
     */
    private String recruityear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_season.recruitSeason
     *
     * @mbg.generated
     */
    private Boolean recruitseason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_season.recruitStartDate
     *
     * @mbg.generated
     */
    private Date recruitstartdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_season.recruitEndDate
     *
     * @mbg.generated
     */
    private Date recruitenddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_season.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_season.isdelete
     *
     * @mbg.generated
     */
    private Boolean isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_season.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_season.createby
     *
     * @mbg.generated
     */
    private Integer createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_season.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_season.updateby
     *
     * @mbg.generated
     */
    private Integer updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    public SchoolRecruitSeason(Integer id, String recruityear, Boolean recruitseason, Date recruitstartdate, Date recruitenddate, Boolean status, Boolean isdelete, Date createtime, Integer createby, Date updatetime, Integer updateby) {
        this.id = id;
        this.recruityear = recruityear;
        this.recruitseason = recruitseason;
        this.recruitstartdate = recruitstartdate;
        this.recruitenddate = recruitenddate;
        this.status = status;
        this.isdelete = isdelete;
        this.createtime = createtime;
        this.createby = createby;
        this.updatetime = updatetime;
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_season
     *
     * @mbg.generated
     */
    public SchoolRecruitSeason() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_season.id
     *
     * @return the value of b_school_recruit_season.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_season.id
     *
     * @param id the value for b_school_recruit_season.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_season.recruitYear
     *
     * @return the value of b_school_recruit_season.recruitYear
     *
     * @mbg.generated
     */
    public String getRecruityear() {
        return recruityear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_season.recruitYear
     *
     * @param recruityear the value for b_school_recruit_season.recruitYear
     *
     * @mbg.generated
     */
    public void setRecruityear(String recruityear) {
        this.recruityear = recruityear == null ? null : recruityear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_season.recruitSeason
     *
     * @return the value of b_school_recruit_season.recruitSeason
     *
     * @mbg.generated
     */
    public Boolean getRecruitseason() {
        return recruitseason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_season.recruitSeason
     *
     * @param recruitseason the value for b_school_recruit_season.recruitSeason
     *
     * @mbg.generated
     */
    public void setRecruitseason(Boolean recruitseason) {
        this.recruitseason = recruitseason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_season.recruitStartDate
     *
     * @return the value of b_school_recruit_season.recruitStartDate
     *
     * @mbg.generated
     */
    public Date getRecruitstartdate() {
        return recruitstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_season.recruitStartDate
     *
     * @param recruitstartdate the value for b_school_recruit_season.recruitStartDate
     *
     * @mbg.generated
     */
    public void setRecruitstartdate(Date recruitstartdate) {
        this.recruitstartdate = recruitstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_season.recruitEndDate
     *
     * @return the value of b_school_recruit_season.recruitEndDate
     *
     * @mbg.generated
     */
    public Date getRecruitenddate() {
        return recruitenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_season.recruitEndDate
     *
     * @param recruitenddate the value for b_school_recruit_season.recruitEndDate
     *
     * @mbg.generated
     */
    public void setRecruitenddate(Date recruitenddate) {
        this.recruitenddate = recruitenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_season.status
     *
     * @return the value of b_school_recruit_season.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_season.status
     *
     * @param status the value for b_school_recruit_season.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_season.isdelete
     *
     * @return the value of b_school_recruit_season.isdelete
     *
     * @mbg.generated
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_season.isdelete
     *
     * @param isdelete the value for b_school_recruit_season.isdelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_season.createtime
     *
     * @return the value of b_school_recruit_season.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_season.createtime
     *
     * @param createtime the value for b_school_recruit_season.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_season.createby
     *
     * @return the value of b_school_recruit_season.createby
     *
     * @mbg.generated
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_season.createby
     *
     * @param createby the value for b_school_recruit_season.createby
     *
     * @mbg.generated
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_season.updatetime
     *
     * @return the value of b_school_recruit_season.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_season.updatetime
     *
     * @param updatetime the value for b_school_recruit_season.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_season.updateby
     *
     * @return the value of b_school_recruit_season.updateby
     *
     * @mbg.generated
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_season.updateby
     *
     * @param updateby the value for b_school_recruit_season.updateby
     *
     * @mbg.generated
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }
}