package com.sundeinfo.kd.zs.dao.model;

import java.util.Date;

public class SchoolRecruitCountingHist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_counting_hist.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_counting_hist.seasonId
     *
     * @mbg.generated
     */
    private Integer seasonid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_counting_hist.schoolId
     *
     * @mbg.generated
     */
    private Integer schoolid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_counting_hist.recruitDate
     *
     * @mbg.generated
     */
    private Date recruitdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_counting_hist.writeDate
     *
     * @mbg.generated
     */
    private Date writedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_counting_hist.undergraduatePeople
     *
     * @mbg.generated
     */
    private Integer undergraduatepeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_counting_hist.technicalPeople
     *
     * @mbg.generated
     */
    private Integer technicalpeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_counting_hist.gkPeople
     *
     * @mbg.generated
     */
    private Integer gkpeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_counting_hist.isdelete
     *
     * @mbg.generated
     */
    private Boolean isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_counting_hist.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_counting_hist.createby
     *
     * @mbg.generated
     */
    private Integer createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_counting_hist.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_counting_hist.updateby
     *
     * @mbg.generated
     */
    private Integer updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_counting_hist
     *
     * @mbg.generated
     */
    public SchoolRecruitCountingHist(Integer id, Integer seasonid, Integer schoolid, Date recruitdate, Date writedate, Integer undergraduatepeople, Integer technicalpeople, Integer gkpeople, Boolean isdelete, Date createtime, Integer createby, Date updatetime, Integer updateby) {
        this.id = id;
        this.seasonid = seasonid;
        this.schoolid = schoolid;
        this.recruitdate = recruitdate;
        this.writedate = writedate;
        this.undergraduatepeople = undergraduatepeople;
        this.technicalpeople = technicalpeople;
        this.gkpeople = gkpeople;
        this.isdelete = isdelete;
        this.createtime = createtime;
        this.createby = createby;
        this.updatetime = updatetime;
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_counting_hist
     *
     * @mbg.generated
     */
    public SchoolRecruitCountingHist() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_counting_hist.id
     *
     * @return the value of b_school_recruit_counting_hist.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_counting_hist.id
     *
     * @param id the value for b_school_recruit_counting_hist.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_counting_hist.seasonId
     *
     * @return the value of b_school_recruit_counting_hist.seasonId
     *
     * @mbg.generated
     */
    public Integer getSeasonid() {
        return seasonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_counting_hist.seasonId
     *
     * @param seasonid the value for b_school_recruit_counting_hist.seasonId
     *
     * @mbg.generated
     */
    public void setSeasonid(Integer seasonid) {
        this.seasonid = seasonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_counting_hist.schoolId
     *
     * @return the value of b_school_recruit_counting_hist.schoolId
     *
     * @mbg.generated
     */
    public Integer getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_counting_hist.schoolId
     *
     * @param schoolid the value for b_school_recruit_counting_hist.schoolId
     *
     * @mbg.generated
     */
    public void setSchoolid(Integer schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_counting_hist.recruitDate
     *
     * @return the value of b_school_recruit_counting_hist.recruitDate
     *
     * @mbg.generated
     */
    public Date getRecruitdate() {
        return recruitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_counting_hist.recruitDate
     *
     * @param recruitdate the value for b_school_recruit_counting_hist.recruitDate
     *
     * @mbg.generated
     */
    public void setRecruitdate(Date recruitdate) {
        this.recruitdate = recruitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_counting_hist.writeDate
     *
     * @return the value of b_school_recruit_counting_hist.writeDate
     *
     * @mbg.generated
     */
    public Date getWritedate() {
        return writedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_counting_hist.writeDate
     *
     * @param writedate the value for b_school_recruit_counting_hist.writeDate
     *
     * @mbg.generated
     */
    public void setWritedate(Date writedate) {
        this.writedate = writedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_counting_hist.undergraduatePeople
     *
     * @return the value of b_school_recruit_counting_hist.undergraduatePeople
     *
     * @mbg.generated
     */
    public Integer getUndergraduatepeople() {
        return undergraduatepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_counting_hist.undergraduatePeople
     *
     * @param undergraduatepeople the value for b_school_recruit_counting_hist.undergraduatePeople
     *
     * @mbg.generated
     */
    public void setUndergraduatepeople(Integer undergraduatepeople) {
        this.undergraduatepeople = undergraduatepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_counting_hist.technicalPeople
     *
     * @return the value of b_school_recruit_counting_hist.technicalPeople
     *
     * @mbg.generated
     */
    public Integer getTechnicalpeople() {
        return technicalpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_counting_hist.technicalPeople
     *
     * @param technicalpeople the value for b_school_recruit_counting_hist.technicalPeople
     *
     * @mbg.generated
     */
    public void setTechnicalpeople(Integer technicalpeople) {
        this.technicalpeople = technicalpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_counting_hist.gkPeople
     *
     * @return the value of b_school_recruit_counting_hist.gkPeople
     *
     * @mbg.generated
     */
    public Integer getGkpeople() {
        return gkpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_counting_hist.gkPeople
     *
     * @param gkpeople the value for b_school_recruit_counting_hist.gkPeople
     *
     * @mbg.generated
     */
    public void setGkpeople(Integer gkpeople) {
        this.gkpeople = gkpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_counting_hist.isdelete
     *
     * @return the value of b_school_recruit_counting_hist.isdelete
     *
     * @mbg.generated
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_counting_hist.isdelete
     *
     * @param isdelete the value for b_school_recruit_counting_hist.isdelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_counting_hist.createtime
     *
     * @return the value of b_school_recruit_counting_hist.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_counting_hist.createtime
     *
     * @param createtime the value for b_school_recruit_counting_hist.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_counting_hist.createby
     *
     * @return the value of b_school_recruit_counting_hist.createby
     *
     * @mbg.generated
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_counting_hist.createby
     *
     * @param createby the value for b_school_recruit_counting_hist.createby
     *
     * @mbg.generated
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_counting_hist.updatetime
     *
     * @return the value of b_school_recruit_counting_hist.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_counting_hist.updatetime
     *
     * @param updatetime the value for b_school_recruit_counting_hist.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_counting_hist.updateby
     *
     * @return the value of b_school_recruit_counting_hist.updateby
     *
     * @mbg.generated
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_counting_hist.updateby
     *
     * @param updateby the value for b_school_recruit_counting_hist.updateby
     *
     * @mbg.generated
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }
}