package com.sundeinfo.kd.zs.dao.model;

public class SchoolRecruitPlanKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_plan.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_plan.schoolId
     *
     * @mbg.generated
     */
    private Integer schoolid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_plan.seasonId
     *
     * @mbg.generated
     */
    private Integer seasonid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    public SchoolRecruitPlanKey(Integer id, Integer schoolid, Integer seasonid) {
        this.id = id;
        this.schoolid = schoolid;
        this.seasonid = seasonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    public SchoolRecruitPlanKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_plan.id
     *
     * @return the value of b_school_recruit_plan.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_plan.id
     *
     * @param id the value for b_school_recruit_plan.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_plan.schoolId
     *
     * @return the value of b_school_recruit_plan.schoolId
     *
     * @mbg.generated
     */
    public Integer getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_plan.schoolId
     *
     * @param schoolid the value for b_school_recruit_plan.schoolId
     *
     * @mbg.generated
     */
    public void setSchoolid(Integer schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_plan.seasonId
     *
     * @return the value of b_school_recruit_plan.seasonId
     *
     * @mbg.generated
     */
    public Integer getSeasonid() {
        return seasonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_plan.seasonId
     *
     * @param seasonid the value for b_school_recruit_plan.seasonId
     *
     * @mbg.generated
     */
    public void setSeasonid(Integer seasonid) {
        this.seasonid = seasonid;
    }
}