package com.sundeinfo.kd.zs.dao.model;

import java.util.Date;

public class SchoolRecruitPlan extends SchoolRecruitPlanKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_plan.recruitCount
     *
     * @mbg.generated
     */
    private Integer recruitcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_plan.undergraduatePeople
     *
     * @mbg.generated
     */
    private Integer undergraduatepeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_plan.technicalPeople
     *
     * @mbg.generated
     */
    private Integer technicalpeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_plan.gkPeople
     *
     * @mbg.generated
     */
    private Integer gkpeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_plan.recruitPlan
     *
     * @mbg.generated
     */
    private Boolean recruitplan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_plan.isdelete
     *
     * @mbg.generated
     */
    private Boolean isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_plan.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_plan.createby
     *
     * @mbg.generated
     */
    private Integer createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_plan.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_recruit_plan.updateby
     *
     * @mbg.generated
     */
    private Integer updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    public SchoolRecruitPlan(Integer id, Integer schoolid, Integer seasonid, Integer recruitcount, Integer undergraduatepeople, Integer technicalpeople, Integer gkpeople, Boolean recruitplan, Boolean isdelete, Date createtime, Integer createby, Date updatetime, Integer updateby) {
        super(id, schoolid, seasonid);
        this.recruitcount = recruitcount;
        this.undergraduatepeople = undergraduatepeople;
        this.technicalpeople = technicalpeople;
        this.gkpeople = gkpeople;
        this.recruitplan = recruitplan;
        this.isdelete = isdelete;
        this.createtime = createtime;
        this.createby = createby;
        this.updatetime = updatetime;
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_recruit_plan
     *
     * @mbg.generated
     */
    public SchoolRecruitPlan() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_plan.recruitCount
     *
     * @return the value of b_school_recruit_plan.recruitCount
     *
     * @mbg.generated
     */
    public Integer getRecruitcount() {
        return recruitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_plan.recruitCount
     *
     * @param recruitcount the value for b_school_recruit_plan.recruitCount
     *
     * @mbg.generated
     */
    public void setRecruitcount(Integer recruitcount) {
        this.recruitcount = recruitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_plan.undergraduatePeople
     *
     * @return the value of b_school_recruit_plan.undergraduatePeople
     *
     * @mbg.generated
     */
    public Integer getUndergraduatepeople() {
        return undergraduatepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_plan.undergraduatePeople
     *
     * @param undergraduatepeople the value for b_school_recruit_plan.undergraduatePeople
     *
     * @mbg.generated
     */
    public void setUndergraduatepeople(Integer undergraduatepeople) {
        this.undergraduatepeople = undergraduatepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_plan.technicalPeople
     *
     * @return the value of b_school_recruit_plan.technicalPeople
     *
     * @mbg.generated
     */
    public Integer getTechnicalpeople() {
        return technicalpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_plan.technicalPeople
     *
     * @param technicalpeople the value for b_school_recruit_plan.technicalPeople
     *
     * @mbg.generated
     */
    public void setTechnicalpeople(Integer technicalpeople) {
        this.technicalpeople = technicalpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_plan.gkPeople
     *
     * @return the value of b_school_recruit_plan.gkPeople
     *
     * @mbg.generated
     */
    public Integer getGkpeople() {
        return gkpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_plan.gkPeople
     *
     * @param gkpeople the value for b_school_recruit_plan.gkPeople
     *
     * @mbg.generated
     */
    public void setGkpeople(Integer gkpeople) {
        this.gkpeople = gkpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_plan.recruitPlan
     *
     * @return the value of b_school_recruit_plan.recruitPlan
     *
     * @mbg.generated
     */
    public Boolean getRecruitplan() {
        return recruitplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_plan.recruitPlan
     *
     * @param recruitplan the value for b_school_recruit_plan.recruitPlan
     *
     * @mbg.generated
     */
    public void setRecruitplan(Boolean recruitplan) {
        this.recruitplan = recruitplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_plan.isdelete
     *
     * @return the value of b_school_recruit_plan.isdelete
     *
     * @mbg.generated
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_plan.isdelete
     *
     * @param isdelete the value for b_school_recruit_plan.isdelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_plan.createtime
     *
     * @return the value of b_school_recruit_plan.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_plan.createtime
     *
     * @param createtime the value for b_school_recruit_plan.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_plan.createby
     *
     * @return the value of b_school_recruit_plan.createby
     *
     * @mbg.generated
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_plan.createby
     *
     * @param createby the value for b_school_recruit_plan.createby
     *
     * @mbg.generated
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_plan.updatetime
     *
     * @return the value of b_school_recruit_plan.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_plan.updatetime
     *
     * @param updatetime the value for b_school_recruit_plan.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_recruit_plan.updateby
     *
     * @return the value of b_school_recruit_plan.updateby
     *
     * @mbg.generated
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_recruit_plan.updateby
     *
     * @param updateby the value for b_school_recruit_plan.updateby
     *
     * @mbg.generated
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }
}