package com.sundeinfo.kd.zs.dao.model;

public class SchoolTeacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_teacher.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_teacher.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_school_teacher.schoolId
     *
     * @mbg.generated
     */
    private Integer schoolid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_teacher
     *
     * @mbg.generated
     */
    public SchoolTeacher(Integer id, Integer userid, Integer schoolid) {
        this.id = id;
        this.userid = userid;
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_school_teacher
     *
     * @mbg.generated
     */
    public SchoolTeacher() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_teacher.id
     *
     * @return the value of b_school_teacher.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_teacher.id
     *
     * @param id the value for b_school_teacher.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_teacher.userId
     *
     * @return the value of b_school_teacher.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_teacher.userId
     *
     * @param userid the value for b_school_teacher.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_school_teacher.schoolId
     *
     * @return the value of b_school_teacher.schoolId
     *
     * @mbg.generated
     */
    public Integer getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_school_teacher.schoolId
     *
     * @param schoolid the value for b_school_teacher.schoolId
     *
     * @mbg.generated
     */
    public void setSchoolid(Integer schoolid) {
        this.schoolid = schoolid;
    }
}